### ISSUE TITLE
Collect info for April meeting | Due by 3/24

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/okcjs-website#105]
Title and description to be used for web post, email announcement, meetup event, and graphics if applicable.

**Title:** Effective Browser JavaScript Debugging

**Date and time:** April 18th 2017 11:30am - 12:30 pm

**Place:** StarSpace46: 1141 W Sheridan Ave, Oklahoma City, OK 73106

**Description:** Did you know that your web browser has a full suite of built-in JavaScript debugging tools? With the developer tools in Chrome, Firefox, and Safari, you can debug JavaScript on the fly with breakpoints, watch expressions, an interactive REPL with autocomplete, and much more. Learn how to troubleshoot bugs and memory leaks like a pro, armed with the same web browser you already use everyday - no extra plugins or downloads required.

**Speaker:** Vance Lucas (@vlucas)

**Speaker bio:** Vance Lucas is a seasoned programmer with nearly two decades of web programming experience dating back to 1998. Vance is a full stack polyglot programmer who currently uses JavaScript/Node.js, PHP, and Ruby. Vance created and maintains the very popular phpdotenv package, Spot ORM, Valitron, and Frisby.js open-source projects, among many others. Vance is the co-founder of the Techlahoma Foundation, Oklahoma City JavaScript User Group (OKC.js), and co-organizer of the annual ThunderPlains Developer Conference in Oklahoma City.

**Comment by seejessicacode** [comment]
@vlucas We just need the talk description and your bio for the meetup details. Thanks for speaking!!

**Comment by vlucas** [comment]
## Effective Browser JavaScript Debugging

Did you know that your web browser has a full suite of built-in JavaScript debugging tools? With the developer tools in Chrome, Firefox, and Safari, you can debug JavaScript on the fly with breakpoints, watch expressions, an interactive REPL with autocomplete, and much more. Learn how to troubleshoot bugs and memory leaks like a pro, armed with the same web browser you already use everyday - no extra plugins or downloads required.

--

Bio: 

Vance Lucas is a seasoned programmer with nearly two decades of web programming experience dating back to 1998. Vance is a full stack polyglot programmer who currently uses JavaScript/Node.js, PHP, and Ruby. Vance created and maintains the very popular phpdotenv package, Spot ORM, Valitron, and Frisby.js open-source projects, among many others. Vance is the co-founder of the Techlahoma Foundation, Oklahoma City JavaScript User Group (OKC.js), and co-organizer of the annual ThunderPlains Developer Conference in Oklahoma City.
