### ISSUE TITLE
Collect info for August meeting | Due ASAP

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/okcjs-website#127]
Title and description to be used for web post, email announcement, meetup event, and graphics if applicable.

**Title:**

**Date and time:** Aug 15th 2017 11:30am - 12:30 pm

**Place:** StarSpace46: 1141 W Sheridan Ave, Oklahoma City, OK 73106

**Description:**

**Speaker:** 

**Speaker bio:**

**Comment by vlucas** [comment]
This month will be split by myself, @vlucas and @the-simian.

Jesse will be presenting on GraphQL/Apollo, and I will be presenting on Fun With ES6 Templates.

Jesse said he would make the poster for the meeting.

**Comment by the-simian** [comment]
Yeah I'm working on it right now
