### ISSUE TITLE
Info about lightning talks, where to sign up, etc.

### ISSUE THREAD

**Issue by the-simian** [techlahoma/okcjs-website#38]
yep. we need it!

**Comment by amandaharlin** [comment]
we also need to state what kinds of computer adapters are available (vga,dvi,gdmi).

maybe this text about what lightning talks are would be of some help? 

>Q: What are Lightning Talks? 
A: The Lightning Talk meetings include lots of interesting *JavaScript* topics in a 5 or 10 minute format. Lightning talks are scheduled for every three months, so please be sure to sign up in our Meetup.com okcjs discussion board if you'd like to participate next time.   

&

>Lightning Talks are a really fun event we put on every 3 months. Community members have 5 to 10 minutes to talk about JavaScript or topics related to JavaScript. We give preference to new speakers to strengthen our community. Common topics include: libraries, ways you've solved problems, what you're working on, or anything relating to JS. To participate: post your topic and presentation length. Please note that marketing pitches are not allowed; lightning talks are a community enrichment event.
