### ISSUE TITLE
Make poster for December meetup | Due 12/2

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/okcjs-website#84]
Lighting Talks no. 15

Details (though should not be needed) at #83

**Comment by DevinClark** [comment]
![2016-december-lightning-talks](https://cloud.githubusercontent.com/assets/353563/20821178/08a8cd8a-b806-11e6-837a-8093476ec630.png)

**Comment by seejessicacode** [comment]
@DevinClark can we get a space between OK and 73106?

**Comment by DevinClark** [comment]
![2016-december-lightning-talks](https://cloud.githubusercontent.com/assets/353563/20854570/a3ef1d80-b8ba-11e6-85ea-cf9a06eda763.png)

**Comment by seejessicacode** [comment]
Excellent response time!!
