### ISSUE TITLE
Collect info for February meeting | Due by 1/27

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/okcjs-website#97]
Title and description to be used for web post, email announcement, meetup event, and graphics if applicable.

**Title:** WebAssembly

**Date and time:** Feb 21st 2017 11:30am - 12:30 pm

**Place:** StarSpace46: 1141 W Sheridan Ave, Oklahoma City, OK 73106

**Description:** WebAssembly is an emerging standard which defines a compact,
efficient, safe, and portable compiler target for the Web. This talk
introduces WebAssembly: what it is and what problems it is designed to
solve. Next, an in-depth tour of WebAssembly: how to compile it, what
it looks like, how it works, how the engine compiles it into efficient
machine code, and how it interfaces with JavaScript. If you care about
alternative programming languages, compiling to the Web, performance,
or you like using powerful JS libraries and frameworks, come learn
about WebAssembly.

**Speaker:** Yury Delendik

**Speaker bio:** Yury Delendik is a Software Engineer at Mozilla Research. His goal is
to provide secure and efficient solutions that work on various
platforms and browsers. The projects he worked on in the past, such as
PDF.js or Shumway, prove that the Web platform can be a valuable
target for more complex applications. At the moment, Yury is
contributing to the WebAssembly project. [@yurydelendik](https://twitter.com/yurydelendik)

**Comment by bshambaugh** [comment]
Does Jessica need help with this?

**Comment by bshambaugh** [comment]
@seejessicacode Do you need help with this?

**Comment by amandaharlin** [comment]
thanks for asking brent. jessica has it.

**Comment by seejessicacode** [comment]
Thanks @bshambaugh! I'm just waiting on the speaker to email the deets. He promised me the info this week.

**Comment by the-simian** [comment]
Also to follow up, idk if you saw but I emailed Yuri / Mozilla back today to follow up on that
