### ISSUE TITLE
Make poster for February meetup | Due 2/3

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/okcjs-website#98]
Meetup details at #97

**Comment by DevinClark** [comment]
![2017-february-wasm](https://cloud.githubusercontent.com/assets/353563/22616664/2e1a1968-ea77-11e6-8772-e9bfbc256bfd.gif)

**Comment by DevinClark** [comment]
![2017-february-wasm](https://cloud.githubusercontent.com/assets/353563/22616667/38d82958-ea77-11e6-907d-2ce5637337cd.png)
In case the gif doesn't work in places.

**Comment by the-simian** [comment]
OMG 
that gif is so badass

**Comment by seejessicacode** [comment]
It's beautiful and I love it! Thanks for the non-gif option too!
